<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1758" started-at="2021-08-22T22:43:48 IST" finished-at="2021-08-22T22:43:50 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="1758" started-at="2021-08-22T22:43:48 IST" finished-at="2021-08-22T22:43:50 IST">
      <class name="com.Test_NGnew.Timeout_Example">
        <test-method status="PASS" signature="executetimeOut()[pri:0, instance:com.Test_NGnew.Timeout_Example@184f6be2]" name="executetimeOut" duration-ms="552" started-at="2021-08-22T22:43:48 IST" finished-at="2021-08-22T22:43:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executetimeOut -->
        <test-method status="FAIL" signature="executetimeOut1()[pri:0, instance:com.Test_NGnew.Timeout_Example@184f6be2]" name="executetimeOut1" duration-ms="1019" started-at="2021-08-22T22:43:48 IST" finished-at="2021-08-22T22:43:49 IST">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.Test_NGnew.Timeout_Example.executetimeOut1() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.Test_NGnew.Timeout_Example.executetimeOut1() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executetimeOut1 -->
        <test-method status="PASS" signature="sampleTestCase()[pri:0, instance:com.Test_NGnew.Timeout_Example@184f6be2]" name="sampleTestCase" duration-ms="13" started-at="2021-08-22T22:43:49 IST" finished-at="2021-08-22T22:43:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- com.Test_NGnew.Timeout_Example -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
